[package]
entrypoint = "src/lib.typ"
name = "hydra"
version = "0.4.0"
compiler = "0.11.0"
authors = ["tinger <me@tinger.dev>"]
repository = "https://github.com/tingerrr/hydra"
description = "Query and display headings of the currently active section"
keywords = ["heading", "introspection"]
license = "MIT"
exclude = ["docs", "examples", "README.md"]
